import mysql from 'mysql2/promise';
import { db, initDatabase } from '../db.ts';
import fs from 'fs';
import path from 'path';

export interface DatabaseCredentials {
  host: string;
  port: number;
  database: string;
  username: string;
  password?: string;
  driver: string;
}

export interface TableColumnInfo {
  name: string;
  type: string;
  nullable: boolean;
  isPrimaryKey: boolean;
  defaultValue: any;
  foreignKey?: {
    table: string;
    toColumn: string;
  };
}

export interface TableSummary {
  name: string;
  rowCount: number;
  columns: TableColumnInfo[];
  description: string;
}

// Default credentials supplied via system environment
export const dbConfig: DatabaseCredentials = {
  host: process.env.DB_HOST || 'localhost',
  port: Number(process.env.DB_PORT) || 3306,
  database: process.env.DB_NAME || 'smart_hospital',
  username: process.env.DB_USERNAME || 'root',
  password: process.env.DB_PASSWORD || 'bitsathy',
  driver: 'MySQL 8.0 / MariaDB (Client: mysql2)'
};

// Friendly table descriptions for hospital domain
const TABLE_DESCRIPTIONS: Record<string, string> = {
  users: 'Core authentication credentials, RBAC roles (ADMIN, DOCTOR, NURSE, PATIENT), contact details, and account hashes.',
  departments: 'Hospital medical wings, clinical departments, floor locations, and bed allocations.',
  doctors: 'Attending physicians, surgeons, specializations, credentials, consultation fees, and availability schedules.',
  nurses: 'Registered nursing personnel, trauma certifications, ward assignments, and real-time workload counters.',
  patients: 'Inpatient and outpatient health records, unique OP numbers, age, triage acuity status, and bed assignments.',
  beds: 'Hospital beds registry, wards, departments, mechanical ventilator support, and real-time occupancy status.',
  bed_allocations: 'Algorithmic audit logs from the Greedy Bed Allocation engine with priority metrics and clinical rationales.',
  appointments: 'Clinical consultation schedule, time-slot collision locks, reason for visit, and booking status.',
  emergency_cases: 'Emergency Department triage queue, Emergency Severity Index (ESI) rating, calculated priority scores.',
  medical_records: 'Electronic Health Records (EHR), clinical consultation summaries, diagnoses, and vital sign logs.',
  prescriptions: 'Pharmacotherapy orders, prescribed medication regimens, dosages, duration, and dispensing status.',
  medical_reports: 'Diagnostic radiology, pathology lab results, ultrasound analyses, and clinical report attachments.',
  equipment: 'Biomedical devices, mechanical ventilators, infusion pumps, serial tracking, and preventive maintenance logs.',
  inventory: 'Pharmaceutical formulary, sterile consumables, surgical packs, reorder thresholds, and unit costs.',
  inventory_transactions: 'Ledger tracking all dispensary stock consumptions, warehouse deliveries, and manual adjustments.',
  nurse_shifts: 'Predictive workload shift roster generated by the constraint-satisfaction nurse shift scheduler.',
  leave_requests: 'Clinical staff time-off requests, vacation approvals, and active availability overrides.',
  notifications: 'Role-targeted urgent hospital alerts, triage dispatches, and inventory low-stock notifications.',
  audit_logs: 'Immutable HIPAA-compliant audit trail recording all patient admissions, discharges, logins, and overrides.',
  facilities: 'Physical infrastructure directory including trauma bays, surgical suites, cafeterias, and hours of operation.',
  ml_training_data: 'Historical 90-day time-series telemetry used to train multivariate regression forecasting algorithms.'
};

/**
 * Test connectivity to MySQL database server using provided or environment credentials
 */
export async function testMysqlConnection(customConfig?: Partial<DatabaseCredentials>) {
  const config = {
    host: customConfig?.host || dbConfig.host,
    port: customConfig?.port || dbConfig.port,
    user: customConfig?.username || dbConfig.username,
    password: customConfig?.password !== undefined ? customConfig.password : dbConfig.password,
    database: customConfig?.database || dbConfig.database,
    connectTimeout: 4000
  };

  const startTime = Date.now();
  try {
    const connection = await mysql.createConnection({
      host: config.host,
      port: config.port,
      user: config.user,
      password: config.password,
      connectTimeout: 4000
    });

    // Check / create database if necessary
    await connection.query(`CREATE DATABASE IF NOT EXISTS \`${config.database}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`);
    await connection.query(`USE \`${config.database}\`;`);
    
    // Check tables
    const [tables] = await connection.query(`SHOW TABLES;`);
    const tableList = Array.isArray(tables) ? tables.map((r: any) => Object.values(r)[0]) : [];

    await connection.end();

    return {
      success: true,
      latencyMs: Date.now() - startTime,
      message: `Successfully connected to MySQL server at ${config.host}:${config.port}! Database '${config.database}' is available.`,
      tableCount: tableList.length,
      tables: tableList,
      config: {
        host: config.host,
        port: config.port,
        database: config.database,
        user: config.user
      }
    };
  } catch (err: any) {
    const isLocalhost = config.host === 'localhost' || config.host === '127.0.0.1';
    let suggestion = '';

    if (err.code === 'ECONNREFUSED' && isLocalhost) {
      suggestion = 'No local MySQL server daemon is currently running on localhost:3306 in this cloud container environment. The application is seamlessly utilizing the embedded relational SQLite engine (ACID compliant with exact identical schema and data). If you have a remote MySQL instance (e.g. Google Cloud SQL, AWS RDS, Supabase, or Clever Cloud), enter its host/IP and credentials to connect.';
    } else if (err.code === 'ER_ACCESS_DENIED_ERROR') {
      suggestion = 'Access denied for specified user and password. Please check your username and password credentials.';
    } else if (err.code === 'ETIMEDOUT' || err.code === 'ENOTFOUND') {
      suggestion = 'Could not reach the database host. Check if the hostname/IP is correct and firewall/port 3306 permits incoming connections.';
    } else {
      suggestion = err.message || 'Connection failed.';
    }

    return {
      success: false,
      latencyMs: Date.now() - startTime,
      errorCode: err.code || 'UNKNOWN_ERROR',
      message: err.message,
      suggestion,
      config: {
        host: config.host,
        port: config.port,
        database: config.database,
        user: config.user
      }
    };
  }
}

/**
 * Executes schema.sql directly into target MySQL instance
 */
export async function applyLocalSchemaToMysql(customConfig?: Partial<DatabaseCredentials>) {
  const config = {
    host: customConfig?.host || dbConfig.host,
    port: customConfig?.port || dbConfig.port,
    user: customConfig?.username || dbConfig.username,
    password: customConfig?.password !== undefined ? customConfig.password : dbConfig.password,
    database: customConfig?.database || dbConfig.database,
    connectTimeout: 5000
  };

  const schemaFile = path.resolve(process.cwd(), 'schema.sql');
  if (!fs.existsSync(schemaFile)) {
    throw new Error('schema.sql file not found in root directory.');
  }

  const sqlScript = fs.readFileSync(schemaFile, 'utf8');

  const connection = await mysql.createConnection({
    host: config.host,
    port: config.port,
    user: config.user,
    password: config.password,
    multipleStatements: true,
    connectTimeout: 5000
  });

  try {
    await connection.query(sqlScript);
    await connection.query(`USE \`${config.database}\`;`);
    const [tables] = await connection.query(`SHOW TABLES;`);
    const tableList = Array.isArray(tables) ? tables.map((r: any) => Object.values(r)[0]) : [];

    await connection.end();

    return {
      success: true,
      message: `Schema successfully created in local MySQL server at ${config.host}:${config.port}! Database '${config.database}' has ${tableList.length} normalized tables.`,
      tableCount: tableList.length,
      tables: tableList,
      database: config.database
    };
  } catch (err: any) {
    await connection.end().catch(() => {});
    throw err;
  }
}

/**
 * Returns overall database status, schema metrics, and active engine configuration
 */
export async function getDatabaseStatus() {
  // Query all SQLite tables
  const tablesResult = db.prepare(`
    SELECT name FROM sqlite_master 
    WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
    ORDER BY name ASC
  `).all() as Array<{ name: string }>;

  let totalRecords = 0;
  for (const t of tablesResult) {
    try {
      const countRes = db.prepare(`SELECT COUNT(*) as count FROM "${t.name}"`).get() as { count: number };
      totalRecords += countRes.count || 0;
    } catch {
      // ignore
    }
  }

  // Quick non-blocking MySQL reachability check
  let mysqlCheckResult: any = null;
  try {
    mysqlCheckResult = await testMysqlConnection();
  } catch (err: any) {
    mysqlCheckResult = {
      success: false,
      message: err.message
    };
  }

  return {
    activeEngine: {
      name: 'SQLite 3 Relational Engine (Embedded ACID)',
      mode: 'Live Operational Database',
      description: 'Zero-latency embedded relational engine supporting all relational joins, foreign keys, and transactions.',
      status: 'ONLINE & HEALTHY',
      totalTables: tablesResult.length,
      totalRecords
    },
    mysqlCredentials: {
      host: dbConfig.host,
      port: dbConfig.port,
      database: dbConfig.database,
      username: dbConfig.username,
      passwordMasked: dbConfig.password ? `${dbConfig.password.slice(0, 3)}••••••••` : '(not set)',
      driver: dbConfig.driver,
      testResult: mysqlCheckResult
    },
    schemaMetadata: {
      ddlFormat: 'MySQL 8.0 & SQLite Relational Compatible',
      foreignKeysEnforced: true,
      walMode: true
    }
  };
}

/**
 * Get schema details and row counts for all tables
 */
export function getAllTablesDetails(): TableSummary[] {
  const tables = db.prepare(`
    SELECT name FROM sqlite_master 
    WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
    ORDER BY name ASC
  `).all() as Array<{ name: string }>;

  const summaries: TableSummary[] = [];

  for (const t of tables) {
    const tableName = t.name;

    // Get row count
    let rowCount = 0;
    try {
      const countRes = db.prepare(`SELECT COUNT(*) as count FROM "${tableName}"`).get() as { count: number };
      rowCount = countRes.count || 0;
    } catch {
      // ignore
    }

    // Get column definitions
    const pragmaColumns = db.prepare(`PRAGMA table_info("${tableName}")`).all() as Array<{
      cid: number;
      name: string;
      type: string;
      notnull: number;
      dflt_value: any;
      pk: number;
    }>;

    // Get foreign keys
    const fks = db.prepare(`PRAGMA foreign_key_list("${tableName}")`).all() as Array<{
      id: number;
      seq: number;
      table: string;
      from: string;
      to: string;
    }>;

    const fkMap = new Map<string, { table: string; toColumn: string }>();
    for (const fk of fks) {
      fkMap.set(fk.from, { table: fk.table, toColumn: fk.to });
    }

    const columns: TableColumnInfo[] = pragmaColumns.map(col => ({
      name: col.name,
      type: col.type || 'TEXT',
      nullable: col.notnull === 0,
      isPrimaryKey: col.pk > 0,
      defaultValue: col.dflt_value,
      foreignKey: fkMap.get(col.name)
    }));

    summaries.push({
      name: tableName,
      rowCount,
      columns,
      description: TABLE_DESCRIPTIONS[tableName] || 'Hospital resource and transactional data table.'
    });
  }

  return summaries;
}

/**
 * Fetch rows from a specific table with pagination and search
 */
export function getTableRows(tableName: string, page = 1, limit = 50, search = '') {
  // Validate table name to prevent SQL injection
  const validTables = db.prepare(`
    SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
  `).all() as Array<{ name: string }>;

  const isValid = validTables.some(t => t.name === tableName);
  if (!isValid) {
    throw new Error(`Table '${tableName}' does not exist in schema.`);
  }

  const offset = (page - 1) * limit;

  // Total count
  const countRes = db.prepare(`SELECT COUNT(*) as count FROM "${tableName}"`).get() as { count: number };
  const total = countRes.count || 0;

  // Query rows
  const rows = db.prepare(`SELECT * FROM "${tableName}" LIMIT ? OFFSET ?`).all(limit, offset);

  return {
    tableName,
    page,
    limit,
    total,
    totalPages: Math.ceil(total / limit) || 1,
    rows
  };
}

/**
 * Safely execute custom SQL query entered by the user
 */
export function executeCustomSql(queryText: string) {
  const trimmed = queryText.trim();
  if (!trimmed) {
    throw new Error('Query text cannot be empty.');
  }

  const startTime = Date.now();
  const isSelect = /^\s*(SELECT|PRAGMA|EXPLAIN|WITH)\b/i.test(trimmed);

  try {
    if (isSelect) {
      const rows = db.prepare(trimmed).all();
      const executionTimeMs = Date.now() - startTime;
      const columns = rows.length > 0 && typeof rows[0] === 'object' && rows[0] !== null
        ? Object.keys(rows[0])
        : [];

      return {
        success: true,
        isSelect: true,
        rowCount: rows.length,
        columns,
        rows: rows.slice(0, 100), // Limit returned preview to 100 rows
        executionTimeMs
      };
    } else {
      const result = db.prepare(trimmed).run();
      const executionTimeMs = Date.now() - startTime;

      return {
        success: true,
        isSelect: false,
        changes: (result as any).changes || 0,
        lastInsertRowid: (result as any).lastInsertRowid,
        executionTimeMs,
        message: `Query executed successfully. ${(result as any).changes || 0} row(s) affected.`
      };
    }
  } catch (err: any) {
    return {
      success: false,
      error: err.message,
      executionTimeMs: Date.now() - startTime
    };
  }
}

/**
 * Reinitialize the database: drop all tables and reload schema and seed data
 */
export function reinitializeDatabase() {
  const tables = db.prepare(`
    SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
  `).all() as Array<{ name: string }>;

  db.exec('PRAGMA foreign_keys = OFF;');
  for (const t of tables) {
    try {
      db.exec(`DROP TABLE IF EXISTS "${t.name}";`);
    } catch {
      // ignore
    }
  }
  db.exec('PRAGMA foreign_keys = ON;');

  // Run full initial schema & seed
  initDatabase();

  return {
    success: true,
    message: 'Database schema successfully re-initialized with all relational constraints, triggers, and seed records.'
  };
}

/**
 * Retrieve the MySQL 8 DDL and seed data scripts
 */
export function getSchemaScripts() {
  const schemaPath = path.resolve(process.cwd(), 'backend/src/main/resources/db/schema.sql');
  const dataPath = path.resolve(process.cwd(), 'backend/src/main/resources/db/data.sql');

  let schemaSql = '';
  let dataSql = '';

  try {
    if (fs.existsSync(schemaPath)) {
      schemaSql = fs.readFileSync(schemaPath, 'utf8');
    }
    if (fs.existsSync(dataPath)) {
      dataSql = fs.readFileSync(dataPath, 'utf8');
    }
  } catch (err) {
    console.error('Error reading schema files:', err);
  }

  return {
    schemaSql,
    dataSql
  };
}
